### ISSUE TITLE
Can upgrade  Exoplayer version ?

### ISSUE THREAD

**Issue by CMingTseng** [warren-bank/Android-RTSP-IPCam-Viewer#2] opened 2019-12-30 18:01 UTC
Dear Sir

Exoplayer new release version is 2.1.1 

some method change !!

can upgrade ? 

i try to  upgrade  but get crash !!

THX

**Comment by warren-bank** [comment] 2019-12-30 20:45
Hi. I'm sorry that the app crashed for you.

This was one of my first Android apps. Having a little more experience with the platform, I'm guessing that the cause for your crash is that:
* the [AndroidManifest.xml](https://github.com/warren-bank/Android-RTSP-IPCam-Viewer/blob/master/RTSP-IPCam-Viewer/src/main/AndroidManifest.xml#L7) is requesting `READ_EXTERNAL_STORAGE`
* this permission is used by [MaterialFilePicker](https://github.com/nbsp-team/MaterialFilePicker)
  - their README specifically says that the app using the library is responsible for checking runtime permissions
    * ~I'm pretty sure that I did not~
    * ~I only tested on Android 4.x~
    * this would effect Android 6.0+

When I do fix this issue (and test the app in a newer version of Android).. I'll also be sure to bump the version of ExoPlayer.
* I still can't use the [official stable release](https://github.com/google/ExoPlayer/releases) because the [pull-request](https://github.com/google/ExoPlayer/pull/3854) that adds RTSP support still hasn't been merged
* but the [dev branch](https://github.com/tresvecesseis/ExoPlayer/tree/dev-v2-rtsp) has made a lot of improvements in the meantime.. which we could benefit from

I'll get around to making these updates in the next few days, and will check back with you here when I have a new release to share.

__update:__

* I spoke too soon..
  - did a quick grep of the code to look for runtime permission management, and it is there.. I must've modified the `MaterialFilePicker` library
    * [..here](https://github.com/warren-bank/Android-libraries/tree/nbsp-team/MaterialFilePicker)
  - here are the important checkpoints that pertain to runtime permission checks:
    * [where the check occurs when the Activity opens](https://github.com/warren-bank/Android-RTSP-IPCam-Viewer/blob/v02.00.00/libs/MaterialFilePicker/src/main/java/com/nbsp/materialfilepicker/ui/FilePickerActivity.java#L67)
    * [where the check occurs if Android version is &gt;= 6.0](https://github.com/warren-bank/Android-RTSP-IPCam-Viewer/blob/v02.00.00/libs/MaterialFilePicker/src/main/java/com/nbsp/materialfilepicker/ui/FilePickerActivity.java#L157)
    * [where the app continues on its merry way after permission is granted](https://github.com/warren-bank/Android-RTSP-IPCam-Viewer/blob/v02.00.00/libs/MaterialFilePicker/src/main/java/com/nbsp/materialfilepicker/ui/FilePickerActivity.java#L171)
  - compared to the [original unmodified Activity](https://github.com/nbsp-team/MaterialFilePicker/blob/aa706eafedbe594b26dd949a55bcff66aec82bf8/library/src/main/java/com/nbsp/materialfilepicker/ui/FilePickerActivity.java#L63) that doesn't include any such checks
* also, I now remember that I did test this app on a 10" Lenovo tablet that's running some flavor of Android 6.x ..and it worked well
* so, my initial guess was wrong..
  - I'm going to need to ask for your help to figure out what the real problem could be..
    1. did the app work when it was first installed?
       - is the crash the result of a particular stream URL?.. or did it just never work at all?
    2. do you have an app on your device that allows you to filter Logcat messages?
       - I tend to use [this one](https://f-droid.org/en/packages/com.dp.logcatapp/)
       - if you could filter messages by the type `error` and/or the string `rtsp`.. could you help me to track down the source of the problem?

**Comment by warren-bank** [comment] 2019-12-30 21:21
Oh.. wait.. I just re-read what you said in your issue..

Please clarify my understanding:

1. did _my_ [release](https://github.com/warren-bank/Android-RTSP-IPCam-Viewer/releases/tag/v02.00.00) build of this app crash on your device?
2. or did you try to upgrade ExoPlayer to the newest official stable release (which doesn't include support for RTSP).. build your own modified version.. and did _that_ build crash on your device?

**Comment by CMingTseng** [comment] 2019-12-31 18:08
Dear Sir

Thx your answer 

this is my doing  {     try to upgrade ExoPlayer to the newest official stable release (which doesn't include support for RTSP).. build your own modified version.. and did that build crash on your device }

and

build your own modified version <---  base your develop  very thx 

i  try modify  it can pass building apk  

but when playing  get Client null ---> crash 

THX

**Comment by warren-bank** [comment] 2019-12-31 23:21
ok.. then you can ignore pretty much everything that I said in my 1st reply; the only important take-away is that if you want to update ExoPlayer and build your own apk.. then you'll need to pull from the HEAD of this [dev branch](https://github.com/tresvecesseis/ExoPlayer/tree/dev-v2-rtsp).. and that will remain the case until the corresponding PR is merged into `master` (of the official repo).

**Closed as completed by warren-bank** 2019-12-31 23:21 UTC

**Comment by CMingTseng** [comment] 2020-01-01 18:33
@warren-bank 

i  fork and modify 

can help me ?

https://github.com/CMingTseng/Android-RTSP-IPCam-Viewer/tree/dev_neo

THX

**Comment by CMingTseng** [comment] 2020-01-01 18:36
> ok.. then you can ignore pretty much everything that I said in my 1st reply; the only important take-away is that if you want to update ExoPlayer and build your own apk.. then you'll need to pull from the HEAD of this [dev branch](https://github.com/tresvecesseis/ExoPlayer/tree/dev-v2-rtsp).. and that will remain the case until the corresponding PR is merged into `master` (of the official repo).

@warren-bank    i also check  tresvecesseis version  

but the version is too old !!

it lost very ....

and  it version can not play rtsp !! <--- i do not know why !! it can pass build

your version it close release-v2   <-- better !!

can help me ?

THX

**Comment by warren-bank** [comment] 2020-01-01 21:29
a few thoughts..

* `tresvecesseis` (and team) are super heros!!
  - the work they did is amazing
  - there is no _my_ version
    * as the ["credits" section in the README](https://github.com/warren-bank/Android-RTSP-IPCam-Viewer#credits) indicates, _my_ repo contains a snapshot of the library written by `tresvecesseis` (and team) at [commit 865ced0](https://github.com/tresvecesseis/ExoPlayer/tree/865ced05b6a1c817d0f2a5f0381b185c4c29bf82/library)
    * this app simply adds some UI that makes use of their work
    * the [current state](https://github.com/tresvecesseis/ExoPlayer/tree/dev-v2-rtsp/library) of their library has made a lot of improvements since that snapshot

* they include a lot of [extensions](https://github.com/tresvecesseis/ExoPlayer/tree/dev-v2-rtsp/extensions) that (for example) the ["main" demo app](https://github.com/tresvecesseis/ExoPlayer/blob/dev-v2-rtsp/demos/main/build.gradle#L73) uses
  - this is all a part of the official [ExoPlayer repo](https://github.com/google/ExoPlayer/tree/release-v2/extensions)
  - I intentionally did not include (nor use) any of these extensions in the app

* as for updating ExoPlayer..
  - I'll copy over an updated snapshot from the [dev branch](https://github.com/tresvecesseis/ExoPlayer/tree/dev-v2-rtsp) and release a new version/build
    * probably later today.. possibly tomorrow

* as for your repo/crashes..
  - I took a quick glance at the commits and don't really follow what you were trying to do
  - after I push my update, you may want to rebase.. though I'd suggest that you avoid the ExoPlayer library directory.. since it will contain the most recent version.. from `tresvecesseis` (and team)

* as for your pull request..
  - I'm glad you find this repo useful
  - I'm not going to merge any of these commits into my repo, but you're of course free to do whatever you like in yours

**Comment by CMingTseng** [comment] 2020-01-02 03:27
very sorry

My English is awful

Can't express my meaning well

I clone  https://github.com/tresvecesseis/ExoPlayer/tree/dev-v2-rtsp-test  <-- branch dev-v2-rtsp-test

But this version

Cannot play RTSP stream  <--- pass build apk 

I manually compared the differences between you and  tresvecesseis_dev-v2-rtsp-test 

Your version is revised / added a lot in the RTSP  ( if need  i can list )

The version of  tresvecesseis_dev-v2-rtsp-test  seems to be quite old. 

There is also a composition of TransferListener  in UdpDataSource/BaseDataSource

But this has been @Deprecated  in later versions

and  the new version 

maybe DRM ?  so  UdpDataSource is final  &  SampleQueue need DrmSessionManager

THX

**Comment by warren-bank** [comment] 2020-01-02 17:15
[here](https://github.com/warren-bank/Android-RTSP-IPCam-Viewer/releases/tag/v02.01.00-alpha.01) is what I came up with.

The library in `tresvecesseis` fork is a little behind the official `master`. I would give those guys some time to iron it out; `master` just released a __bunch__ of breaking changes.

My version is a bit of a hack.. attempting to merge the conflict between the two code-bases. For a while, it felt like a game of whack-a-mole.. for every API I patched.. there would be 2 new errors. Total waste of time.. but the apk works.. so I guess that's something :)

**Comment by CMingTseng** [comment] 2020-01-08 09:19
Dear Sir

1. 
i try  use &  modify  your new version

if use your  core & ui library  at Google Exoplayer Demo app

will  get 

 AGPBI: {"kind":"error","text":"Program type already present: com.google.android.exoplayer2.AudioBecomingNoisyManager$AudioBecomingNoisyReceiver","sources":[{}],"tool":"D8"}
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: com.google.android.exoplayer2.AudioBecomingNoisyManager$AudioBecomingNoisyReceiver  

but i check  AudioBecomingNoisyManager  AudioBecomingNoisyReceiver 


2. if not modify   just  unzip & clean and build project  (v02.01.00-alpha.01)

i can not look any rtsp  (but logcat  show   message   the application handshake rtsp  )

THX

**Comment by warren-bank** [comment] 2020-01-08 13:53
1. regarding updating the rest of `tresvecesseis` ExoPlayer fork..<br>including modified versions of official demos
   - I made a comment in the corresponding open PR.. if they ask for assistance, then I will
   - seems that Google has no intention to merge this library..<br>not sure how much maintenance it's going to see from the community
2. regarding building the updated apk from my `v02.01.00-alpha.01` tag
   - works for me
     * no errors building
     * rtsp streams play fine

fwiw.. _duplicate classes_ implies that you're importing the `ui` library twice; you should check your code.

**Comment by CMingTseng** [comment] 2020-01-09 04:56
> 1. regarding updating the rest of `tresvecesseis` ExoPlayer fork..including modified versions of official demos
>    
>    * I made a comment in the corresponding open PR.. if they ask for assistance, then I will
>    * seems that Google has no intention to merge this library..not sure how much maintenance it's going to see from the community
> 2. regarding building the updated apk from my `v02.01.00-alpha.01` tag
>    
>    * works for me
>      
>      * no errors building
>      * rtsp streams play fine
> 
> fwiw.. _duplicate classes_ implies that you're importing the `ui` library twice; you should check your code.


Dear Sir

as general develop

we . like use  jenter /   bintray to get  library 

like this :

dependencies {
   implementation group: 'com.google.android.exoplayer', name: 'core', version: '2.9.2'
   implementation     "com.google.android.exoplayer:ui:2.9.2"
}

as you say  { . seems that Google has no intention to merge this library ..}

so  i try to export & refactoring the RTSP library  as  Google project Structure

let other develop can use 

dependencies {
   implementation group: 'com.google.android.exoplayer', name: 'core', version: '2.9.2'
   implementation     "com.google.android.exoplayer:ui:2.9.2"
   implementation group: 'com.google.android.exoplayer', name: 'extra-core', version: '0.0.1'
   implementation     "com.google.android.exoplayer:extra-ui:0.0.1"
 implementation     "com.google.android.exoplayer:extension-sdp:0.0.1"
 implementation     "com.google.android.exoplayer:extension-rtp:0.0.1"
 implementation     "com.google.android.exoplayer:extension-rtsp:0.0.1"
}

 it  seem ok ?? !!  <--- pass build apk 

But   i can not play RTSP ?? (it seem work  i can see logcat get information )

not any streaming . show at screen !!!

{

01-09 12:19:19.379 13457-13659/com.github.warren_bank.rtsp_ipcam_viewer V/Receiver: RTSP/1.0 200 OK
    CSeq: 3
    Transport: RTP/AVP;unicast;client_port=59446-59447;server_port=50024-50025;ssrc=DA8B1BCB;mode="PLAY"
    Server: GStreamer RTSP server
    Session: u3wAm6BMU3DXa$gJ; timeout=60
    Date: Thu, 09 Jan 2020 04:19:19 GMT
01-09 12:19:19.388 13457-13660/com.github.warren_bank.rtsp_ipcam_viewer V/Sender: PLAY rtsp://8.42.69.117:554/axis-media/media.amp?videocodec=h264&resolution=1280x720 RTSP/1.0
    CSeq: 4
    User-Agent: ExoPlayerLib/2.11.1 (Media Player for Android)
    Session: u3wAm6BMU3DXa$gJ;
    Range: npt=0.000-
    Scale: 1.0


}

can  fixed ?

PS .  your v02.01.00-alpha.01   ---> some devices ok . some devices only handshake rtsp no streaming at screen 

THX

**Comment by warren-bank** [comment] 2020-01-09 05:43
Please don't take this the wrong way.. but until somebody on `tresvecesseis` dev team asks me for a contribution.. I'm done making changes.

If they released their code under a suitable public license.. then I suppose that you're free to publish your own version. Personally, I think that's disrespectful to the original authors.. considering they've been trying to get the code merged for a long time now, and if anybody deserves proper credit.. they do.

OK.. that's about all I have to say on the topic.

**Comment by CMingTseng** [comment] 2021-11-10 07:34
now  Exoplayer office support RTSP


https://exoplayer.dev/rtsp.html

**Comment by warren-bank** [comment] 2021-11-12 10:08
Hi. I just updated ExoPlayer to r2.16.0 ..which is the most recent stable release. As you said, RTSP is now officially supported.. so the experimental dependency is no-longer needed.
