### ISSUE TITLE
no authentication support?

### ISSUE THREAD

**Issue by Unixware** [warren-bank/Android-RTSP-IPCam-Viewer#11] opened 2022-05-15 10:39 UTC
App works with the provided URLs but when trying to see my own camera says "Unfortunately, RTSP IP-Cam Viewer has syopped"
I bet this app does not support pass protected rtsp streams ?  thx

the URL is like this :
rtsp://user:pass@xxx.xxxx.xxxx.xxxx:554/live/ch0

**Comment by warren-bank** [comment] 2022-05-16 17:12
This little app offloads all RTSP playback to the ExoPlayer library, which [the docs](https://exoplayer.dev/rtsp.html#authentication) say does support BASIC and DIGEST authentication by embedding `user:pass` into the URL as you have done. Any incompability issue is really a question for [their dev team](https://github.com/google/ExoPlayer/issues); I don't know anything about the internals. Apologies.

Having said that, the app shouldn't crash when it encounters a video URL that it can't play. Any chance of seeing a logcat error that shows a strack trace to help identify where the error originates (and could be caught)? If not.. no problem.. I could probably figure it out without a trace.. but I'm not going to get around to looking at it for at least a few days.

**Comment by Unixware** [comment] 2022-05-16 19:01
no worries, it is an old phone (4.4.4) , I ve trimmed the logcat from when your app starts
[log.txt](https://github.com/warren-bank/Android-RTSP-IPCam-Viewer/files/8702713/log.txt)

**Comment by warren-bank** [comment] 2022-05-17 15:20
Thanks for the log! Seems to be a _NullPointerException_ that happens in the method [_prepareExoPlayer_](https://github.com/warren-bank/Android-RTSP-IPCam-Viewer/blob/v02.02.00/android-studio-project/RTSP-IPCam-Viewer/src/main/java/com/github/warren_bank/rtsp_ipcam_viewer/common/helpers/ExoPlayerUtils.java#L127).. which is called from [here](https://github.com/warren-bank/Android-RTSP-IPCam-Viewer/blob/v02.02.00/android-studio-project/RTSP-IPCam-Viewer/src/main/java/com/github/warren_bank/rtsp_ipcam_viewer/fullscreen_view/activities/VideoActivity.java#L40).

**Comment by warren-bank** [comment] 2022-05-17 20:01
thoughts..
* adding a try/catch is the obvious workaround to prevent a crash, but it doesn't address why your RTSP stream isn't playing
* I'd be curious to know whether [ExoAirPlayer](https://github.com/warren-bank/Android-ExoPlayer-AirPlay-Receiver/releases) can play your RTSP stream
  - it's another app that I wrote
  - it's a more general-purpose video player (with an HTTP "cast" API) that also uses ExoPlayer
  - a lot more work has gone into this app, and it initializes MediaItem objects very differently
  - it also supports RTSP video stream URLs
    * the easiest way to test it with one is to enter the RTSP video stream URL into this ["sender"](http://webcast-reloaded.surge.sh/airplay_sender.html)
    * I'm currently looking for a public IP cam that serves an RTSP stream with a URL that includes (demo) auth credentials.. but I'm have a hard time finding any that would make for a good test case
* neither app currently supports RTMP
  - feels like an oversight, since ExoPlayer does include an optional extension to add support for these streams
  - I'll probably look into adding this (to both) in the near future

**Comment by Unixware** [comment] 2022-05-17 20:09
thanks again, but as I wrote above "no worries" - could be issue with the codecs of the android I m trying, an old Sony with unofficial ROM (**4.4.4**) -  , many thanks for the help, take your time with this ...:-)

**Comment by warren-bank** [comment] 2022-05-17 20:17
I never worry.. but that said, I am curious if my apps have a bug that should be fixed.

[This](https://github.com/google/ExoPlayer/issues/9544) recent issue appears to support that there is.. and that the underlying problem was with ExoPlayer's implementation.. which was fixed only a few days ago. Once they push a stable update, I'll publish updated releases for my apps (to use it). When that happens, I'd be curious to know if it fixes your issue.

**Comment by warren-bank** [comment] 2022-05-17 20:24
regarding the demo RTSP stream they use in that issue to test..

[This](https://ipvm.com/forums/video-surveillance/topics/need-rtsp-url-to-test-with) website lists both:
* [rtsp://demo:demo@ipvmdemo.dyndns.org:5541/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast](rtsp://demo:demo@ipvmdemo.dyndns.org:5541/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast)
* [rtsp://demo:demo@ipvmdemo.dyndns.org:5542/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast](rtsp://demo:demo@ipvmdemo.dyndns.org:5542/onvif-media/media.amp?profile=profile_1_h264&sessiontimeout=60&streamtype=unicast)

..but the server that the dynamic dns record resolves to is currently offline;
I'll check again later.. maybe it'll be available at another time.

**Comment by warren-bank** [comment] 2022-05-17 22:42
PS: I just found another bug that's completely unrelated to basic/digest auth..

I feel really dumb that I didn't originally test for this.. or maybe it was introduced later.. idk.

In any case.. when a low-res url is specified, but high-res is left blank.. then:
* the low-res plays in list/grid view
* when clicked to play fullscreen.. crash.. burn
  - the app tests for a null value, but the value is actually given an empty string by default
  - I'll fix this later tonight
  - it's very possible that this was the cause of your problem.. because it also results in a _NullPointerException_
    * as a test, just copy the same url that you used for low-res into the high-res field
    * to edit an existing video entry, click on its name (need to aim for the text)

**Comment by warren-bank** [comment] 2022-05-19 06:58
I added several commits today.. making all of the fixes/improvements mentioned here. [v02.03.00](https://github.com/warren-bank/Android-RTSP-IPCam-Viewer/releases/tag/v02.03.00) is the newest release. I'll update again when ExoPlayer releases its next stable version.. to incorporate their fix for Basic auth.

**Comment by Unixware** [comment] 2022-05-19 07:06
cheers !

**Closed as completed** 2022-05-19 16:10 UTC
